### ISSUE TITLE
Awesome Font

### ISSUE THREAD

**Issue by jhhuynh42** [eezcommerce/eezcommerce#94]
Contribue or credit Awesome Font

**Comment by tselouie** [comment]
what do u mean?

**Comment by jhhuynh42** [comment]
Emile wanted us to credit whoever made Awesome Font for legal reasons

**Comment by tselouie** [comment]
its free and open-source though..

**Comment by jhhuynh42** [comment]
We told Emile that. He went into story about how one group almost got school sued and they had to buy 10 copies of the games to compensate.
